# GoReleaser configuration for Scotter
version: 2

before:
  hooks:
    - go mod tidy
    - go test -v ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/caezarr-oss/scotter/pkg/version.version={{.Version}} -X github.com/caezarr-oss/scotter/pkg/version.commit={{.Commit}} -X github.com/caezarr-oss/scotter/pkg/version.date={{.Date}} -X github.com/caezarr-oss/scotter/pkg/version.builtBy=goreleaser

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # No format overrides needed as Windows is not supported

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

sboms:
  - artifacts: archive
